<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/epaiement-up2pay/magento2/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/epaiement-up2pay/magento2/blob/master/LICENSE
 */

?>
<form id="CreditAgricole_PaymentGateway_credit_card_three_d_form" method="<?= $this->getMethod() ?>" action="<?= $this->getAction() ?>">
    <?php foreach($this->getFormFields() as $name => $value): ?>
        <input type="hidden" name="<?= $name ?>" value="<?= $value ?>" />
    <?php endforeach; ?>
</form>
