version: '3.0'
services:
  web:
    container_name: "${MAGENTO_CONTAINER_NAME}"
    build: .
    ports:
      - "9090:80"
    links:
      - db
    env_file:
      - .env
    environment:
      MAGENTO_URL: "${NGROK_URL}"
    volumes:
      - ".:/magento2-plugin"
  db:
    image: mysql:5.6.23
    ports:
      - ${MYSQL_PORT_OUT}:${MYSQL_PORT_IN}
    env_file:
      - .env
